# Generated by Django 3.0.5 on 2021-01-19 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('ACCOUNT_NO', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('TRANSACTION_ID', models.CharField(max_length=100)),
                ('PART_TRAN_ID', models.CharField(max_length=100)),
                ('TRANSACTION_AMOUNT', models.CharField(max_length=100)),
                ('TRANSACTION_TYPE', models.CharField(max_length=100)),
                ('TRANSACTION_SOURCE', models.CharField(max_length=100)),
                ('ACTIVE_TRANSACTION_ID', models.CharField(max_length=100)),
                ('TRANSACTION_CATEGORY', models.CharField(max_length=100)),
                ('NARRATION', models.CharField(max_length=100)),
                ('RECONCILIATION_REMARKS', models.CharField(max_length=100)),
                ('TRAN_DATE', models.DateField(blank=True)),
                ('TRAN_TIME', models.DateTimeField(default=datetime.datetime.now)),
                ('VALUE_DATE', models.DateField(blank=True)),
                ('VALUE_TIME', models.DateTimeField(default=datetime.datetime.now)),
                ('POSTED_TIME', models.DateTimeField(default=datetime.datetime.now)),
                ('POSTED_BY', models.CharField(max_length=100)),
                ('APPROVED_DATE', models.DateField(blank=True)),
                ('APPROVED_TIME', models.DateTimeField(default=datetime.datetime.now)),
                ('APPROVED_BY', models.CharField(max_length=100)),
                ('HASH_VALUE', models.BinaryField()),
                ('DELETED_FLAG', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('ACCOUNT_ID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('CREATED_BY', models.CharField(max_length=100)),
                ('DATE_CREATED', models.CharField(max_length=100)),
                ('TIME_CREATED', models.DateTimeField(default=datetime.datetime.now)),
                ('UPDATED_BY', models.CharField(max_length=100)),
                ('TIME_UPDATED', models.DateTimeField(default=datetime.datetime.now)),
                ('TRANSACTION_SOURCE', models.CharField(max_length=100)),
                ('APPROVED_BY', models.CharField(max_length=100)),
                ('DATE_APPROVED', models.DateField(blank=True)),
                ('TIME_APPROVED', models.DateTimeField(default=datetime.datetime.now)),
                ('STATUS', models.CharField(max_length=100)),
                ('HASH_VALUE', models.BinaryField()),
                ('DELETED_FLAG', models.CharField(max_length=100)),
                ('ROW_VERSION', models.CharField(max_length=100)),
                ('CUSTOMER_ID', models.CharField(max_length=100)),
                ('DATE_UPDATED', models.DateField(blank=True)),
                ('ACCOUNT_CODE_ID', models.CharField(max_length=100)),
                ('ACCOUNT_NO', models.CharField(max_length=100)),
                ('ACCOUNT_NAME', models.CharField(max_length=100)),
                ('ACCOUNT_NO_ALIAS', models.CharField(max_length=100)),
                ('ACCOUNT_NO_ALIAS_INDEX', models.CharField(max_length=100)),
                ('CLEARED_BALANCE', models.CharField(max_length=100)),
                ('UNCLEARED_BALANCE', models.CharField(max_length=100)),
                ('LIEN_AMOUNT', models.CharField(max_length=100)),
                ('OVERDRAFT_LIMIT', models.CharField(max_length=100)),
                ('FREEZE_CODE', models.CharField(max_length=100)),
                ('CURRENCY', models.CharField(max_length=100)),
                ('ENABLE_SMS_ALERT', models.CharField(max_length=100)),
                ('ENABLE_EMAIL_ALERT', models.CharField(max_length=100)),
                ('MONTHLY_STATEMENT', models.CharField(max_length=100)),
                ('ANNUAL_STATEMENT', models.CharField(max_length=100)),
                ('CURRENT_INTEREST_RATE', models.CharField(max_length=100)),
                ('LAST_CHARGES_RUN_DATE', models.DateTimeField()),
                ('LAST_CHARGES_RUN_TIME', models.DateTimeField()),
                ('CUSTOMER_DETAIL_ID', models.CharField(max_length=100)),
                ('LAST_TRANSACTION_DATE', models.DateField(blank=True)),
                ('LAST_TRANSACTION_TIME', models.DateTimeField(default=datetime.datetime.now)),
                ('LAST_INTEREST_RUN_DATE', models.DateField(default=datetime.datetime.now)),
                ('LAST_INTEREST_RUN_TIME', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
